name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "wnews"
database_id = "6a9bae44-5608-4820-b76c-c9885807ef55"
